[project]
name = "investment-trader"
version = "0.1.0"
description = "My attempt at creating an agentic investment bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.11.11",
]
